

import {
  LayoutDashboard,
  Users,
  Briefcase,
  Newspaper,
  MessageSquare,
  Info,
  FileText,
  ShieldCheck,
  Calendar,
  Contact,
  Clock,
  Folder,
  Mail,
  Calculator,
  Beaker,
  Lightbulb,
  Settings,
  LogOut,
  FilePlus2,
  Database,
  Bug,
  Bell,
  HeartPulse,
  BarChart3,
  DatabaseBackup,
  Wand2,
  Landmark,
  Megaphone,
  PackageSearch,
  Users2,
  Share2,
  Contact2,
  HardHat,
  ArrowDownAZ,
  Trash2,
  ListTodo,
  ImageIcon,
  BookText,
  BrainCircuit,
  GitMerge,
  Pencil,
  ListChecks,
  FilePenLine,
  Route,
  Link as LinkIcon,
  FileOutput,
  FileDigit,
  TrendingUp,
  TrendingDown,
  WalletCards,
  UserPlus,
  Banknote,
  Percent,
  FileSignature,
  ListPlus,
  FileInput,
  Activity,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface MenuItem {
  href: string;
  label: string;
  icon: LucideIcon;
}

export const accountingMenuItems: MenuItem[] = [
    { href: "/accounting/invoices/create", icon: FileDigit, label: "Create Invoice" },
    { href: "/accounting/accounts-receivable", icon: FileOutput, label: "Accounts Receivable" },
    { href: "/accounting/service-items", icon: ListPlus, label: "Service Items" },
    { href: "/accounting/ledgers?tab=income", icon: TrendingUp, label: "Manage Income" },
    { href: "/accounting/ledgers?tab=expenses", icon: TrendingDown, label: "Manage Expenses" },
    { href: "/accounting/ledgers", icon: BookText, label: "General Ledger" },
    { href: "/accounting/reports/income-statement", icon: FileText, label: "Income Statement"},
    { href: "/accounting/tax/sales-tax", icon: Percent, label: "Sales Tax Calculator" },
    { href: "/accounting/accounts-payable", icon: FileInput, label: "Accounts Payable" },
    { href: "/accounting/bank-statements", icon: WalletCards, label: "Bank Statements" },
    { href: "/accounting/asset-management", icon: WalletCards, label: "Capital Assets" },
    { href: "/accounting/payroll", icon: Banknote, label: "Payroll" },
    { href: "/accounting/reports", icon: BarChart3, label: "Reporting Hub" },
    { href: "/accounting/tax", icon: ShieldCheck, label: "Tax Center" },
    { href: "/accounting/tax/categories", icon: FileSignature, label: "Tax Categories" },
    { href: "/accounting/vitals", icon: Activity, label: "Financial Vitals" },
    { href: "/accounting/onboarding", icon: UserPlus, label: "Client Onboarding" },
    { href: "/accounting/bks", icon: Info, label: "BKS Welcome" },
];


export const allMenuItems: MenuItem[] = [
  { href: "/action-manager", label: "Action Manager", icon: LayoutDashboard },
  { href: "/master-mind", label: "Task & Event Mngr", icon: BrainCircuit },
  { href: "/workflow-chart", label: "Workflow Chart", icon: GitMerge },
  { href: "/command-centre", label: "Command Centre", icon: BrainCircuit },
  { href: "/action-manager/manage", label: "Manage Dashboard", icon: LayoutDashboard },
  { href: "/action-manager/trash", label: "Trash", icon: Trash2 },
  { href: "/a-z-sort", label: "A-Z Sort", icon: ArrowDownAZ },
  { href: "/hr-manager", label: "HR Manager", icon: Contact2 },
  { href: "/social-media-manager", label: "Social Media", icon: Share2 },
  { href: "/crm", label: "CRM", icon: Users2 },
  { href: "/inventory-manager", label: "Inventory", icon: PackageSearch },
  { href: "/marketing-manager", label: "Marketing", icon: Megaphone },
  { href: "/google", label: "Google Apps", icon: Wand2 },
  { href: "/backup", label: "Backup", icon: DatabaseBackup },
  { href: "/reports", label: "Reports", icon: BarChart3 },
  { href: "/hytexercise", label: "Hytexercise", icon: HeartPulse },
  { href: "/alerts", label: "Alerts", icon: Bell },
  { href: "/my-worker", label: "My Worker", icon: HardHat },
  { href: "/debug", label: "Debug", icon: Bug },
  { href: "/bug-repair", label: "Bug Repair", icon: Bug },
  { href: "/data", label: "Data", icon: Database },
  { href: "/dev-notes", label: "Dev Notes", icon: BookText },
  { href: "/forms", label: "Forms", icon: FilePlus2 },
  { href: "/image-generator", label: "Image Generation", icon: ImageIcon },
  { href: "/settings", label: "Settings", icon: Settings },
  { href: "/logout", label: "Logout", icon: LogOut },
  { href: "/ogeemail", label: "OgeeMail", icon: Mail },
  { href: "/ogeemail/compose", label: "Compose Email", icon: Pencil },
  { href: "/communications", label: "Communications", icon: MessageSquare },
  { href: "https://messages.google.com/web", label: "Text Messages", icon: MessageSquare },
  { href: "/contacts", label: "Contacts", icon: Contact },
  { href: "/projects", label: "Projects", icon: Briefcase },
  { href: "/all-project-tasks", label: "All Project Tasks", icon: ListTodo },
  { href: "/to-do", label: "A To Do List", icon: ListChecks },
  { href: "/calendar", label: "Calendar", icon: Calendar },
  { href: "/document-manager", label: "Document Manager", icon: Folder },
  { href: "/idea-board", label: "Idea Board", icon: Lightbulb },
  { href: "/research", label: "Research", icon: Beaker },
  { href: "/sandbox", label: "Sandbox", icon: Beaker },
  { href: "/accounting", label: "Accounting", icon: Calculator },
  ...accountingMenuItems,
];

    