
import {
  LayoutDashboard,
  Users,
  Briefcase,
  Newspaper,
  MessageSquare,
  Info,
  FileText,
  ShieldCheck,
  Calendar,
  Contact,
  Clock,
  Folder,
  Mail,
  Calculator,
  Beaker,
  Lightbulb,
  Settings,
  LogOut,
  FilePlus2,
  Database,
  Bug,
  Bell,
  HeartPulse,
  BarChart3,
  DatabaseBackup,
  Wand2,
  Landmark,
  Megaphone,
  PackageSearch,
  Users2,
  Share2,
  Contact2,
  HardHat,
  ArrowDownAZ,
  Trash2,
  ListTodo,
  ImageIcon,
  BookText,
  BrainCircuit,
  GitMerge,
  Pencil,
  ListChecks,
  FilePenLine,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface MenuItem {
  href: string;
  label: string;
  icon: LucideIcon;
}

export const allMenuItems: MenuItem[] = [
  { href: "/action-manager", label: "Action Manager", icon: LayoutDashboard },
  { href: "/master-mind", label: "The Ultimate Task & Event Manager", icon: BrainCircuit },
  { href: "/knowledge-base", label: "Knowledge Base", icon: BrainCircuit },
  { href: "/doc-editor", label: "Text Editor", icon: FilePenLine },
  { href: "/workflow-chart", label: "Workflow Chart", icon: GitMerge },
  { href: "/command-centre", label: "Command Centre", icon: BrainCircuit },
  { href: "/action-manager/manage", label: "Manage Dashboard", icon: LayoutDashboard },
  { href: "/action-manager/trash", label: "Trash", icon: Trash2 },
  { href: "/a-z-sort", label: "A-Z Sort", icon: ArrowDownAZ },
  { href: "/hr-manager", label: "HR Manager", icon: Contact2 },
  { href: "/social-media-manager", label: "Social Media", icon: Share2 },
  { href: "/crm", label: "CRM", icon: Users2 },
  { href: "/inventory-manager", label: "Inventory", icon: PackageSearch },
  { href: "/marketing-manager", label: "Marketing", icon: Megaphone },
  { href: "/legal-hub", label: "Legal Hub", icon: Landmark },
  { href: "/google", label: "Google Apps", icon: Wand2 },
  { href: "/backup", label: "Backup", icon: DatabaseBackup },
  { href: "/reports", label: "Reports", icon: BarChart3 },
  { href: "/hytexercise", label: "Hytexercise", icon: HeartPulse },
  { href: "/alerts", label: "Alerts", icon: Bell },
  { href: "/my-worker", label: "My Worker", icon: HardHat },
  { href: "/debug", label: "Debug", icon: Bug },
  { href: "/data", label: "Data", icon: Database },
  { href: "/dev-notes", label: "Dev Notes", icon: BookText },
  { href: "/forms", label: "Forms", icon: FilePlus2 },
  { href: "/image-generator", label: "Image Generation", icon: ImageIcon },
  { href: "/settings", label: "Settings", icon: Settings },
  { href: "/logout", label: "Logout", icon: LogOut },
  { href: "/ogeemail", label: "OgeeMail", icon: Mail },
  { href: "/ogeemail/compose", label: "C.Mail", icon: Pencil },
  { href: "/communications", label: "Communications", icon: MessageSquare },
  { href: "/contacts", label: "Contacts", icon: Contact },
  { href: "/projects", label: "Projects", icon: Briefcase },
  { href: "/project-status", label: "Project Status", icon: ListChecks },
  { href: "/tasks", label: "Tasks", icon: ListTodo },
  { href: "/calendar", label: "Calendar", icon: Calendar },
  { href: "/files", label: "File Cabinet", icon: Folder },
  { href: "/idea-board", label: "Idea Board", icon: Lightbulb },
  { href: "/research", label: "Research", icon: Beaker },
  { href: "/accounting", label: "Accounting", icon: Calculator },
];
