import {
  LayoutDashboard,
  Users,
  Briefcase,
  Newspaper,
  MessageSquare,
  Info,
  FileText,
  ShieldCheck,
  Calendar,
  Contact,
  Clock,
  Folder,
  Mail,
  Calculator,
  Beaker,
  Lightbulb,
  Settings,
  LogOut,
  FilePlus2,
  Database,
  Bug,
  Bell,
  HeartPulse,
  BarChart3,
  DatabaseBackup,
  Wand2,
  Landmark,
  Megaphone,
  PackageSearch,
  Users2,
  Share2,
  Contact2,
  HardHat,
  ArrowDownAZ,
  Trash2,
  ListTodo,
  ImageIcon,
  BookText,
  BrainCircuit,
  GitMerge,
  Pencil,
  ListChecks,
  FilePenLine,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { ManageFilesView } from "@/components/files/manage-files-view";

export default function ManageFilesPage() {
    return <ManageFilesView />;
}
